import { Button, VerticalBox, HorizontalBox, TextEdit, ListView } from "std-widgets.slint";
import { GameSave } from "GameSaveComponent.slint";

export component AppWindow inherits Window {
    title: "Rusty Hex Coincidence Finder";
    min-height: 390pt;
    min-width: 280pt;

    max-height: 540pt;
    max-width: 420pt;

    in-out property <[{gamesave_name: string, gamesave_path: string}]> gamesave_list;
    in-out property <[int]> gamesave_values;
    property <int> index: 0;

    out property <string> selected-modify-value <=> modify-value.text;

    in-out property <bool> checked-for-coincidences: true;
    in-out property <[{coincidence_line: int, coincidence_index: int}]> found-coincidences-list: [
        {
            coincidence-line: 0,
            coincidence-index: 0
        }
    ];

    callback request-add-savegame();
    callback request-remove-savegame(name: string);
    callback update-savegame-value(name: string, value: string);
    callback request-refresh();

    callback request-modify-coincidence(index: int);

    VerticalBox {
        padding: 8pt;

        VerticalLayout {
            padding: 4pt;
            spacing: 4pt;
            alignment: start;

            max-height: 780pt;
            max-width: 960pt;

            Text {
                text: "Savegame files";
                font-size: 18pt;
                horizontal-alignment: center;
                vertical-alignment: top;
            }

            /////////////////////////////////
            // Savegame table descriptions //
            /////////////////////////////////
            if gamesave_list.length > 0: HorizontalLayout {
                padding-top: 10pt;
                padding-left: 3pt;
                padding-right: 3pt;

                Text {
                    horizontal-alignment: left;
                    vertical-alignment: bottom;

                    text: "value";
                    color: darkgrey;
                    font-italic: true;
                }

                Text {
                    horizontal-alignment: center;
                    vertical-alignment: bottom;

                    text: "file name";
                    color: darkgrey;
                    font-italic: true;
                }

                Text {
                    horizontal-alignment: right;
                    vertical-alignment: bottom;

                    text: "delete";
                    color: darkgrey;
                    font-italic: true;
                }
            }

            ///////////////
            // Savegames //
            ///////////////
            if gamesave_list.length == 0: HorizontalLayout {
                padding: 4pt;
                height: 48px;

                Rectangle {
                    background: #222222;
                    border-radius: 4pt;

                    Text {
                        text: "No savegame added yet...";
                        color: darkslategray;
                        font-italic: true;
                        font-size: 10pt;
                    }
                }
            }

            for gs in gamesave_list: GameSave {
                name: gs.gamesave_name;
                remove-click => {
                    checked-for-coincidences = false;
                    root.request-remove-savegame(gs.gamesave_name);
                }
                update-value => {
                    checked-for-coincidences = false;
                    root.update-savegame-value(self.name, self.value);
                }
            }

            ///////////////////////
            // Check/Add buttons //
            ///////////////////////

            HorizontalLayout {
                spacing: 4pt;

                Button {
                    min-height: 24pt;
                    max-width: 32pt;

                    text: "Check";
                    primary: false;
                    enabled: gamesave_list.length > 0 ? true
                                                  : false;

                    clicked => {
                        root.request-refresh();
                    }
                }

                Button {
                    max-height: 24pt;

                    text: "Add savegame";
                    primary: false;

                    clicked => {
                        root.request-add-savegame();
                    }
                }
            }

        }

        /////////////////////
        // Value selection //
        /////////////////////

        HorizontalLayout {
            spacing: 16pt;
            alignment: center;

            Text {
                vertical-alignment: center;
                font-size: 12pt;
                color: #eeeeee;
                text: "New value:";
            }

            Rectangle {
                background: #292929;
                border-radius: 6px;
                min-width: 64pt;
                min-height: 24pt;

                modify-value:= TextInput {
                    horizontal-alignment: center;
                    vertical-alignment: center;

                    selection-background-color: #99bbaa;
                    selection-foreground-color: #000000;

                    font-size: 12pt;
                    color: lightseagreen;
                    input-type: number;
                    single-line: true;

                    max-width: 128pt;

                    text: "255";

                    accessible-placeholder-text: "new value";

                    visible: true;
                }
            }
        }

        //////////////////
        // Mid "screen" //
        //////////////////

        Rectangle {
            min-height: 60pt;

            background: #212424;
            border-radius: 4pt;
            vertical-stretch: 1.0;

            //////////////////////
            // Coincidence list //
            //////////////////////

            VerticalLayout {
                min-height: 60pt;
                alignment: center;
                vertical-stretch: 1.0;

                Rectangle {
                    vertical-stretch: 1.0;
                    height: !checked-for-coincidences ? 24pt : 0pt;
                    visible: !checked-for-coincidences;

                    Text {
                        vertical-alignment: center;
                        horizontal-alignment: center;
                        font-size: 20px;

                        text: !checked-for-coincidences ? "Refresh to search\nfor coincidences"
                                                       : "No coincidences found...";
                        color: !checked-for-coincidences ? lightblue
                                                        : #ff6666;
                    }
                }

                Rectangle {
                    visible: checked-for-coincidences;

                    VerticalLayout {
                        alignment: start;

                        Text {
                            height: 24pt;
                            horizontal-alignment: center;
                            font-size: 20phx;

                            text: found-coincidences-list.length == 1 ? "Found 1 coincidence"
                                                           : "Found \{root.found-coincidences-list.length} coincidences";
                            color: found-coincidences-list.length == 1 ? palegreen
                                                            : lightgoldenrodyellow;
                        }

                        Text {
                            height: 14pt;
                            horizontal-alignment: center;
                            font-size: 12phx;

                            text: "Select a coincidence to modify";
                            color: #aaaaaa;
                            font-italic: true;
                        }

                        ListView {
                            height: checked-for-coincidences ? 142pt : 0pt;
                            visible: checked-for-coincidences;

                            for item in found-coincidences-list: Rectangle {
                                height: 30pt;

                                Button {
                                    height: 24pt;
                                    width: 120px;
                                    text: "line " + item.coincidence-line;
                                    primary: true;

                                    clicked => {
                                        request-modify-coincidence(item.coincidence-index);
                                    }
                                }
                            }
                        }

                    }
                }
            }
        }
    }
}